### ISSUE TITLE
I get page not found and 404 request

### ISSUE THREAD

**Issue by kcibdev** [RavenPayAfrica/atlas-webpay-node-sdk#1]
## Bug report

- react-atlast-pay version: ^1.0.5
- Affected browsers (and versions): Brave

### Current behaviour

Whenever i try to close the payment window i get the error
Which says 
`GET https://elaborate-blancmange-d0d15d.netlify.app/undefined?trx_ref=undefined&merchant_ref=undefined&status=undefined 404`

Image below

![image](https://github.com/RavenPayAfrica/atlas-webpay-node-sdk/assets/32621169/fbe44b9d-1e82-446d-8e1e-02b0d7a9b0e6)

And also in your documentation i saw this code as
 ```
if (atlasEvent.type === 'onClose') {
      // do something here if user closes the window
}
```

but when i console log it, it was `onclose` small letter

```ts
// put code here
const [pay, atlastEvent] = useAtlasPay()

const handlePayment = async (price: string) => {

        if (!session) return error("You must be logged in to pay")

        const configData = {
            customer_email: email,
            description: name,
            merchant_ref: ref,
            amount: price,
            redirect_url: "",
            // payment_methods: "card", "bank_transfer", "ussd", "raven",
            secret_key: process.env.PAYMENT_SECRET_KEY,
        };

        const payResult = await pay(configData)
    }

    useEffect(() => {
        if (atlastEvent?.type.toString().toLowerCase() === "onclose") {
            error(atlastEvent?.message)
        }

        console.log(atlastEvent)
    }, [atlastEvent])
```

[issue demo](https://codesandbox.io/)

### Expected behaviour

_Please explain how you'd expect it to behave._

If i wish to cancel payment, the modal should just close instead of showing that error

**Comment by Raaja0007** [comment]
i think it is a typo error in the calling and if validation

**Comment by mona-chen** [comment]
Hello thanks for bringing this to notice, we will make a fix and update you about this issue, additionally by default - AtlasPay doesnt close the modal because there is an option for the user to specify a `redirect_url` which a user gets redirected to `onSuccess` or `onClose`; however a developer might instead decide to close the AtlasPay Window by calling AtlasPay.shutdown() within the onClose function.

I hope that makes sense 🙂
